[env:lilygo_t5_213]
platform = espressif32
board = esp32dev
framework = arduino
board_build.flash_size = 4MB
board_build.partitions = custom_partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2@^1.5.9
