#!/usr/bin/env python3
"""
Convert TTF/OTF to Adafruit GFX font header for GxEPD2 / Arduino.

Usage:
  python font_convert.py <font.ttf> <size_pt> <VarName> [options]

Options:
  --dpi N          Rendering DPI (default: 141).  Display is ~105 DPI;
                   higher values give larger pixel size at same point size.
  --threshold N    1-bit cutoff 0-255 (default: 100).  Lower = more pixels
                   filled (thicker); higher = fewer pixels (thinner).
  --mono           Use freetype monochrome hinting instead of grayscale
                   threshold (old behaviour; often gives uneven strokes).

Examples:
  python font_convert.py fonts/AtkinsonHyperlegible-Regular.ttf  8 AtkinsonHyperlegible_Regular8pt7b
  python font_convert.py fonts/SourceSerif4-Regular.ttf          8 SourceSerif4_Regular8pt7b
  python font_convert.py fonts/SourceCodePro-Regular.ttf         7 SourceCodePro_Regular7pt7b
  python font_convert.py fonts/SourceCodePro-Regular.ttf         5 SourceCodePro_Regular5pt7b

  # Thicker strokes (better for very small sizes):
  python font_convert.py fonts/AtkinsonHyperlegible-Regular.ttf  6 AtkinsonHyperlegible_Regular6pt7b --threshold 80

Font download links (all free/open-source):
  Atkinson Hyperlegible : https://brailleinstitute.org/freefont
  Source Serif 4        : https://fonts.google.com/specimen/Source+Serif+4
  Source Code Pro       : https://fonts.google.com/specimen/Source+Code+Pro

Output goes to ../src/fonts/<VarName>.h

Requires:
  pip install freetype-py
"""

import sys, os, argparse

try:
    import freetype
except ImportError:
    print("Missing dependency. Run:  pip install freetype-py")
    sys.exit(1)

FIRST_CHAR = 0x20   # space
LAST_CHAR  = 0x7E   # tilde
DEFAULT_DPI = 141
DEFAULT_THRESHOLD = 100


def convert(ttf_path: str, size_pt: int, varname: str,
            dpi: int = DEFAULT_DPI, threshold: int = DEFAULT_THRESHOLD,
            mono: bool = False) -> str:
    face = freetype.Face(ttf_path)
    face.set_char_size(size_pt * 64, 0, dpi, 0)

    if mono:
        load_flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO
    else:
        # Grayscale anti-aliased rendering.  The auto-hinter typically gives
        # more uniform stroke widths than the font's native mono hints, which
        # is the main cause of the "sometimes 1, sometimes 2 pixels wide"
        # artifact on low-DPI B&W e-paper panels.
        load_flags = (freetype.FT_LOAD_RENDER |
                      freetype.FT_LOAD_TARGET_NORMAL |
                      freetype.FT_LOAD_FORCE_AUTOHINT)

    bitmap_data: list[int] = []
    glyphs: list[tuple] = []

    for char_code in range(FIRST_CHAR, LAST_CHAR + 1):
        glyph_idx = face.get_char_index(char_code)
        face.load_glyph(glyph_idx, load_flags)
        slot = face.glyph
        bm   = slot.bitmap

        w  = bm.width
        h  = bm.rows
        xo = slot.bitmap_left
        yo = -slot.bitmap_top
        xa = (slot.advance.x + 32) >> 6   # round to nearest pixel

        glyph_offset = len(bitmap_data)

        bits: list[int] = []

        if mono:
            # 1-bit packed rows — original behaviour
            for row in range(h):
                for col in range(w):
                    byte_idx = row * bm.pitch + (col >> 3)
                    bit_idx  = 7 - (col & 7)
                    bits.append(1 if (bm.buffer[byte_idx] & (1 << bit_idx)) else 0)
        else:
            # 8-bit grayscale rows — threshold to 1-bit.
            # pitch == w in NORMAL mode (one byte per pixel, no padding).
            for row in range(h):
                for col in range(w):
                    gray = bm.buffer[row * bm.pitch + col]
                    bits.append(1 if gray >= threshold else 0)

        # Pad to byte boundary
        while len(bits) % 8:
            bits.append(0)

        # Pack into bytes (MSB first)
        for i in range(0, len(bits), 8):
            b = 0
            for j in range(8):
                b = (b << 1) | bits[i + j]
            bitmap_data.append(b)

        glyphs.append((glyph_offset, w, h, xa, xo, yo))

    y_advance = face.size.height >> 6

    mode_desc = (f"mono" if mono
                 else f"grayscale threshold={threshold}")

    # ---- Build header -------------------------------------------------------
    lines = [
        f"// Font: {os.path.basename(ttf_path)}, {size_pt}pt, DPI={dpi}, {mode_desc}",
        f"// Generated by tools/font_convert.py — do not edit by hand",
        f"#pragma once",
        f"#include <Adafruit_GFX.h>",
        "",
    ]

    # Bitmap array
    lines.append(f"static const uint8_t {varname}Bitmaps[] PROGMEM = {{")
    row: list[str] = []
    for i, b in enumerate(bitmap_data):
        row.append(f"0x{b:02X}")
        if len(row) == 16 or i == len(bitmap_data) - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines += ["};", ""]

    # Glyph array
    lines.append(f"static const GFXglyph {varname}Glyphs[] PROGMEM = {{")
    for i, (off, w, h, xa, xo, yo) in enumerate(glyphs):
        c = chr(FIRST_CHAR + i)
        label = repr(c) if c.isprintable() and c != "\\" else f"0x{FIRST_CHAR+i:02X}"
        lines.append(f"  {{{off:6d}, {w:3d}, {h:3d}, {xa:3d}, {xo:4d}, {yo:4d} }},  // {label}")
    lines += ["};", ""]

    # Font struct
    lines += [
        f"static const GFXfont {varname} PROGMEM = {{",
        f"  (uint8_t  *){varname}Bitmaps,",
        f"  (GFXglyph *){varname}Glyphs,",
        f"  0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {y_advance}",
        "};",
        "",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Convert TTF to Adafruit GFX font header")
    p.add_argument("ttf",       help="Path to TTF/OTF file")
    p.add_argument("size_pt",   type=int, help="Font size in points")
    p.add_argument("varname",   help="C variable name (e.g. MyFont8pt7b)")
    p.add_argument("--dpi",       type=int, default=DEFAULT_DPI,
                   help=f"Rendering DPI (default {DEFAULT_DPI})")
    p.add_argument("--threshold", type=int, default=DEFAULT_THRESHOLD,
                   help=f"Grayscale cutoff 0-255 (default {DEFAULT_THRESHOLD})")
    p.add_argument("--mono",      action="store_true",
                   help="Use monochrome hinting instead of grayscale threshold")
    args = p.parse_args()

    if not os.path.isfile(args.ttf):
        print(f"Error: file not found: {args.ttf}")
        sys.exit(1)

    content = convert(args.ttf, args.size_pt, args.varname,
                      dpi=args.dpi, threshold=args.threshold, mono=args.mono)

    out_dir  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "fonts")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{args.varname}.h")

    with open(out_path, "w") as f:
        f.write(content)

    print(f"Written: {out_path}")
