#!/usr/bin/env python3
"""
Generate compact hyphenation trie data from pyphen en_US dictionary.

Outputs:
  - src/hyphenation_data.h
  - src/hyphenation_data.cpp
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

import pyphen


ALLOWED = set(".abcdefghijklmnopqrstuvwxyz'")
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
H_PATH = SRC / "hyphenation_data.h"
CPP_PATH = SRC / "hyphenation_data.cpp"


@dataclass
class TrieNode:
    children: Dict[str, "TrieNode"] = field(default_factory=dict)
    pat_index: int = -1
    index: int = -1


def build_patterns() -> List[Tuple[str, int, Tuple[int, ...]]]:
    hd = pyphen.Pyphen(lang="en_US").hd
    patterns = hd.patterns

    out: List[Tuple[str, int, Tuple[int, ...]]] = []
    for key, (offset, values) in patterns.items():
        if any(ch not in ALLOWED for ch in key):
            continue
        out.append((key, offset, values))
    out.sort(key=lambda x: x[0])
    return out


def build_trie(patterns: List[Tuple[str, int, Tuple[int, ...]]]):
    root = TrieNode()
    for pidx, (key, _off, _vals) in enumerate(patterns):
        n = root
        for ch in key:
            n = n.children.setdefault(ch, TrieNode())
        n.pat_index = pidx

    nodes: List[TrieNode] = [root]
    root.index = 0
    i = 0
    while i < len(nodes):
        n = nodes[i]
        for ch in sorted(n.children.keys()):
            c = n.children[ch]
            if c.index < 0:
                c.index = len(nodes)
                nodes.append(c)
        i += 1

    edge_ch: List[int] = []
    edge_next: List[int] = []
    node_edge_start: List[int] = []
    node_edge_count: List[int] = []
    node_pat_index: List[int] = []

    for n in nodes:
        node_edge_start.append(len(edge_ch))
        kids = sorted(n.children.items(), key=lambda kv: kv[0])
        node_edge_count.append(len(kids))
        node_pat_index.append(n.pat_index if n.pat_index >= 0 else 0xFFFF)
        for ch, child in kids:
            edge_ch.append(ord(ch))
            edge_next.append(child.index)

    return (
        node_edge_start,
        node_edge_count,
        node_pat_index,
        edge_ch,
        edge_next,
    )


def pack_values(patterns: List[Tuple[str, int, Tuple[int, ...]]]):
    nibble_vals: List[int] = []
    pat_offset: List[int] = []
    pat_vals_start: List[int] = []
    pat_vals_len: List[int] = []

    for _key, offset, values in patterns:
        pat_offset.append(offset)
        pat_vals_start.append(len(nibble_vals))
        pat_vals_len.append(len(values))
        for v in values:
            if v < 0 or v > 15:
                raise ValueError(f"value out of nibble range: {v}")
            nibble_vals.append(v)

    packed: List[int] = []
    i = 0
    while i < len(nibble_vals):
        hi = nibble_vals[i]
        lo = nibble_vals[i + 1] if i + 1 < len(nibble_vals) else 0
        packed.append((hi << 4) | lo)
        i += 2

    return pat_offset, pat_vals_start, pat_vals_len, packed, len(nibble_vals)


def emit_u8_array(name: str, values: List[int], cols: int = 16) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(values), cols):
        chunk = values[i : i + cols]
        lines.append("  " + ", ".join(f"0x{v:02X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_nodes(node_edge_start, node_edge_count, node_pat_index) -> str:
    lines = ["const HyNode HY_NODES[] PROGMEM = {"]
    for s, c, p in zip(node_edge_start, node_edge_count, node_pat_index):
        lines.append(f"  {{ {s}, {c}, {p} }},")
    lines.append("};")
    return "\n".join(lines)


def emit_edges(edge_ch, edge_next) -> str:
    lines = ["const HyEdge HY_EDGES[] PROGMEM = {"]
    for ch, nxt in zip(edge_ch, edge_next):
        lines.append(f"  {{ {ch}, {nxt} }},")
    lines.append("};")
    return "\n".join(lines)


def emit_patterns(pat_offset, pat_vals_start, pat_vals_len) -> str:
    lines = ["const HyPat HY_PATS[] PROGMEM = {"]
    for o, s, l in zip(pat_offset, pat_vals_start, pat_vals_len):
        lines.append(f"  {{ {o}, {s}, {l} }},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    patterns = build_patterns()
    max_pat_len = max(len(k) for k, _o, _v in patterns)

    (
        node_edge_start,
        node_edge_count,
        node_pat_index,
        edge_ch,
        edge_next,
    ) = build_trie(patterns)

    pat_offset, pat_vals_start, pat_vals_len, vals_packed, nibble_count = pack_values(patterns)

    header = f"""#pragma once
#include <Arduino.h>

// Generated by tools/gen_hyphenation_data.py from pyphen en_US patterns.
// Uses Knuth-Liang pattern dictionary (ASCII subset).

struct HyNode {{
  uint16_t edge_start;
  uint16_t edge_count;
  uint16_t pat_index; // 0xFFFF = none
}};

struct __attribute__((packed)) HyEdge {{
  uint8_t  ch;
  uint16_t next;
}};

struct __attribute__((packed)) HyPat {{
  uint8_t  offset;
  uint16_t vals_start_nibble;
  uint8_t  vals_len;
}};

constexpr uint16_t HY_NODE_COUNT = {len(node_edge_start)};
constexpr uint16_t HY_EDGE_COUNT = {len(edge_ch)};
constexpr uint16_t HY_PAT_COUNT = {len(pat_offset)};
constexpr uint16_t HY_VAL_NIBBLE_COUNT = {nibble_count};
constexpr uint8_t  HY_MAX_PATTERN_LEN = {max_pat_len};

extern const HyNode  HY_NODES[];
extern const HyEdge  HY_EDGES[];
extern const HyPat   HY_PATS[];
extern const uint8_t HY_VALS_PACKED[];
"""

    cpp_parts = [
        '#include "hyphenation_data.h"',
        "",
        emit_nodes(node_edge_start, node_edge_count, node_pat_index),
        "",
        emit_edges(edge_ch, edge_next),
        "",
        emit_patterns(pat_offset, pat_vals_start, pat_vals_len),
        "",
        emit_u8_array("HY_VALS_PACKED", vals_packed),
        "",
    ]
    cpp = "\n".join(cpp_parts)

    H_PATH.write_text(header, encoding="utf-8", newline="\n")
    CPP_PATH.write_text(cpp, encoding="utf-8", newline="\n")

    print(f"wrote {H_PATH}")
    print(f"wrote {CPP_PATH}")
    print(
        "stats:",
        f"patterns={len(patterns)}",
        f"nodes={len(node_edge_start)}",
        f"edges={len(edge_ch)}",
        f"nibbles={nibble_count}",
        f"packed_bytes={len(vals_packed)}",
        f"max_pat_len={max_pat_len}",
    )


if __name__ == "__main__":
    main()

