// Single translation unit that owns all font data.
// Never include font/*.h files anywhere else.
#include "fonts.h"
#include "fonts/AtkinsonHyperlegible_Regular6pt7b.h"
#include "fonts/AtkinsonHyperlegible_Regular8pt7b.h"
#include "fonts/AtkinsonHyperlegible_Regular10pt7b.h"
#include "fonts/AtkinsonHyperlegible_Bold6pt7b.h"
#include "fonts/AtkinsonHyperlegible_Bold8pt7b.h"
#include "fonts/AtkinsonHyperlegible_Bold10pt7b.h"
#include "fonts/SourceSerif4_Regular6pt7b.h"
#include "fonts/SourceSerif4_Regular7pt7b.h"
#include "fonts/SourceSerif4_Regular9pt7b.h"
#include "fonts/SourceSerif4_SemiBold6pt7b.h"
#include "fonts/SourceSerif4_SemiBold7pt7b.h"
#include "fonts/SourceSerif4_SemiBold9pt7b.h"
#include "fonts/SourceCodePro_Regular5pt7b.h"
#include "fonts/SourceCodePro_Regular7pt7b.h"
