#pragma once
#include <Arduino.h>

// Generated by tools/gen_hyphenation_data.py from pyphen en_US patterns.
// Uses Knuth-Liang pattern dictionary (ASCII subset).

struct HyNode {
  uint16_t edge_start;
  uint16_t edge_count;
  uint16_t pat_index; // 0xFFFF = none
};

struct __attribute__((packed)) HyEdge {
  uint8_t  ch;
  uint16_t next;
};

struct __attribute__((packed)) HyPat {
  uint8_t  offset;
  uint16_t vals_start_nibble;
  uint8_t  vals_len;
};

constexpr uint16_t HY_NODE_COUNT = 13669;
constexpr uint16_t HY_EDGE_COUNT = 13668;
constexpr uint16_t HY_PAT_COUNT = 9782;
constexpr uint16_t HY_VAL_NIBBLE_COUNT = 23283;
constexpr uint8_t  HY_MAX_PATTERN_LEN = 28;

extern const HyNode  HY_NODES[];
extern const HyEdge  HY_EDGES[];
extern const HyPat   HY_PATS[];
extern const uint8_t HY_VALS_PACKED[];
